### ISSUE TITLE
Testimonial Star rating always shows as 5 regardless 

### ISSUE THREAD

**Issue by HeatherHowardVoice** [CallumHoward/daisy-voice#10]
I had a 4.3 or something which should probably have rounded down rather than up and also a testimonial that didn't have a star rating attached at all that I tried to put as 0

**Comment by CallumHoward** [comment]
@HeatherHowardVoice now closed, now the field in Sanity will only allow entering whole numbers

**Comment by HeatherHowardVoice** [comment]
5 Stars show on the testimonials regardless of what number is input via Sanity editor. A "5 stars displayed" or "no stars displayed" binary option would be fine if that's easier than creating 0-5 star options, possibly even preferable. Thank you. -H

**Comment by tekhuynh** [comment]
I don't remember exactly what we were doing in our last session to have missed this. I will look into this tonight and hopefully have a fix by tomorrow.

**Comment by tekhuynh** [comment]
confirm if fixed @HeatherHowardVoice @CallumHoward

**Comment by CallumHoward** [comment]
Confirmed fixed!

**Comment by CallumHoward** [comment]
Actually it seems like 0 stars doesn't work (reverts to 5)
